// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:5554313c-d01f-4903-a4b3-0944cbf4c1b5",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_sbv9FQOqJ",
    "aws_user_pools_web_client_id": "1p65p7tbev7uk4g477rt4949c8"
};


export default awsmobile;
